#!/usr/bin/env python3
'''Floor hash-guard: verify .claude/CLAUDE-FLOOR.md matches its .sha256 sidecar.
Generated by the .dev-knowledge floor carrier (ADR-78, ADR-93). Do not hand-edit the
floor; regenerate from the hub instead. Two legs run this: the commit-time pre-commit
hook (permissive on absent), and the session-start settings.json hook with
--require-present (a deleted-but-tracked floor then fails loud).'''
import hashlib
import re
import sys
from pathlib import Path

FLOOR = Path(".claude/CLAUDE-FLOOR.md")
SIDECAR = Path(".claude/CLAUDE-FLOOR.md.sha256")


def _norm(text):
    return text.replace("\r\n", "\n").replace("\r", "\n")


def main():
    require_present = "--require-present" in sys.argv[1:]
    if not FLOOR.exists():
        if require_present:
            print("floor absent: .claude/CLAUDE-FLOOR.md is missing but required -- "
                  "restore with `git checkout HEAD -- .claude/CLAUDE-FLOOR.md`.",
                  file=sys.stderr)
            return 1
        return 0  # floor not adopted here; nothing to verify
    actual = hashlib.sha256(
        _norm(FLOOR.read_text(encoding="utf-8")).encode("utf-8")).hexdigest()
    if not SIDECAR.exists():
        print("CLAUDE-FLOOR.md.sha256 sidecar missing -- regenerate via the hub "
              "generator.", file=sys.stderr)
        return 1
    m = re.search(r"[0-9a-f]{64}", SIDECAR.read_text(encoding="utf-8"))
    expected = m.group(0) if m else ""
    if actual != expected:
        print("floor hash drift: %s != sidecar %s -- regenerate via the hub "
              "generator, or restore with `git checkout HEAD -- "
              ".claude/CLAUDE-FLOOR.md`." % (actual[:12], expected[:12]),
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
